lang: "de_DE"
title: Cashflow Kompass
short_name: Cashflow Kompass
email: thomas.huebner@finum.ag
tel: +49 (0) 176 3290 7225
author: Thomas Hübner
address: >
  Fürther Straße 244b<br/>
    90429 Nürnberg
description: > # this means to ignore newlines until "show_excerpts:"
  Arbeite nicht nur für
  dein Geld – Lass dein
  Geld für dich arbeiten!

logo: assets/img/CashflowKompass/cashflow-kompass-black.svg

show_excerpts: false # set to true to show excerpts on the homepage

# Contact
static_email: "https://formspree.io/your-email@domain.com"

# Analytics
analytics:
  provider: true # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: UA-178230864-1
#  facebookpixel:
#    tracking_id: 716482995548219

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
#    twitter: jekyllrb
#    github:  jekyll
#    rss: rss
    # dribbble: jekyll
#     facebook: jekyll
    # flickr:   jekyll
     instagram: cashflow_kompass
#     linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Defaults
defaults:
  # default
  - scope:
      path: ""
    values:
      amp-sidebar: true

  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      meta: BlogPosting
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
      header: true
      footer: false

# Collections
collections:
  feedbacks:
    output: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Reading Files
include:
  - .htaccess
  - _pages

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll-sitemap
